AWSTemplateFormatVersion: '2010-09-09'
Description: Using GitHub Actions to deploy CloudFormation stacks Demo

Parameters:
  BucketName:
    Description: Name your Bucket
    Default: mysamplebucket-12345
    Type: String

# Just for demo purposes, this bucket will be public
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Join
        - '-'
        - - !Ref BucketName
          - !Ref 'AWS::StackName'
