Resources:
  Instance01:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-00a929b66ed6e0de6
      InstanceType: t2.micro
      # BlockDeviceMappings:
      # - DeviceName: /dev/xvda
      #   Ebs:
      #     VolumeSize: 10
      #     VolumeType: gp3
