name: Deploy CloudFormation Stacks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cfn-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials & region
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      # - name: Deploy S3 Buckets CloudFormation Stacks
      #   id: S3-bucket
      #   uses: aws-actions/aws-cloudformation-github-deploy@v1
      #   with:
      #     name: s3-bucket-02
      #     template: CloudFormation/01_s3_bucket.yaml
      #     no-fail-on-empty-changeset: "1"

      - name: Deploy EC2 Instance CloudFormation Stacks
        id: EC2-instance
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ec2-instance-01
          template: CloudFormation/02-ec2.yaml
          no-fail-on-empty-changeset: "1"
